version: "3.9"

name: enterprise-data-engineering

services:

  postgres:
    image: postgres:16
    container_name: enterprise_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./warehouse:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - enterprise_network

  redis:
    image: redis:7-alpine
    container_name: enterprise_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - enterprise_network

  spark-master:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: spark-master

    hostname: spark-master

    environment:
      SPARK_MODE: master

    ports:
      - "7077:7077"
      - "8080:8080"

    volumes:
      - ./:/opt/project

    networks:
      - enterprise_network

  spark-worker:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: spark-worker

    hostname: spark-worker

    depends_on:
      - spark-master

    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077

    volumes:
      - ./:/opt/project

    networks:
      - enterprise_network

volumes:
  postgres_data:

networks:
  enterprise_network: