version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: enterprise_postgres

    restart: always

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: enterprise_dw

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./warehouse:/docker-entrypoint-initdb.d

    networks:
      - enterprise

  spark-master:
    image: bitnami/spark:3.5

    container_name: spark-master

    hostname: spark-master

    environment:
      - SPARK_MODE=master

    ports:
      - "7077:7077"
      - "8080:8080"

    volumes:
      - ./:/opt/project

    networks:
      - enterprise

  spark-worker:

    image: bitnami/spark:3.5

    container_name: spark-worker

    depends_on:
      - spark-master

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

    ports:
      - "8081:8081"

    volumes:
      - ./:/opt/project

    networks:
      - enterprise

  airflow:

    image: apache/airflow:2.10.0

    container_name: airflow

    restart: always

    depends_on:
      - postgres

    ports:
      - "8088:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES=False

    volumes:
      - ./airflow/dags:/opt/airflow/dags

    networks:
      - enterprise

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: streamlit

    depends_on:
      - postgres

    ports:
      - "8501:8501"

    volumes:
      - ./:/app

    networks:
      - enterprise

volumes:
  postgres_data:

networks:
  enterprise: